# Dockerfile

FROM python:3.9

WORKDIR /app

COPY . .

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    hashlib \
    sqlite3 \
    && pip install --no-cache-dir 

EXPOSE 1234

CMD ["python", "server.py"]

#run with the command:
    #docker run -p 1234:1234 -v /path/on/host:/app/data my-python-app
    #after the docker image is built from the dockerfile
    
